name: YT Highlights

on:
  workflow_dispatch:  # Permette l'esecuzione manuale
  schedule:
    - cron: '*/15 * * * *'  # Esegue ogni 15 minuti

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 yt-dlp
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run SkyStreaming scraper
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python update_m3u.py

      - name: Run combine_m3u8 script
        run: |
          python ythigh.py

      - name: Commit and push updated M3U8 files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add highlights.m3u8
          git add output/*.m3u8 output/*.ts
          git commit -m "Aggiornato file M3U8 con nuovi flussi" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true
