name: Update itaevents2.m3u8

on:
  workflow_dispatch:  # Permette l'esecuzione manuale
  schedule:
    - cron: '*/15 * * * *'  # Esegue ogni 15 minuti

jobs:
  update-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pygithub

      - name: Run M3U8 updater
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python modify_m3u8.py

      - name: Commit and push updated M3U8 file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add itaevents2.m3u8
          git commit -m "Aggiornato itaevents2.m3u8 con nuove header" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true
