name: Update itaevents2.m3u8

# Trigger del workflow
on:
  push:  # Si attiva ad ogni push
    branches: [ main ]
  schedule:  # Si attiva anche ogni ora (opzionale)
    - cron: '0 * * * *'
  workflow_dispatch:  # Permette esecuzione manuale

jobs:
  update-m3u8:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout del repository
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Configura Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    # Installa dipendenze
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pygithub
    
    # Esegui lo script
    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token fornito da GitHub
      run: |
        python modify_m3u8.py
    
    # Commit e push delle modifiche
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add itaevents2.m3u8
        git diff --staged --quiet || git commit -m "Aggiornamento automatico itaevents2.m3u8"
        git push
