name: Update SportsOnline M3U8 Playlist

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Playlist Update Script
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python sportsonline_script.py

      - name: Commit Updated Playlist
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sportsonline_playlist.m3u8
          if git status | grep -q "Changes to be committed"; then
            git commit -m "Update M3U8 playlist for SportsOnline"
            git push
          else
            echo "Nessuna modifica da committare."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
