name: Update SportsOnline M3U8 Playlist

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your preferred Python version

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Run the script
      - name: Run Playlist Update Script
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python sportsonline_script.py

      # Commit and push changes if any
      - name: Commit Updated Playlist
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sportsonline_playlist.m3u8
          git diff --staged --quiet || git commit -m "Update M3U8 playlist for SportsOnline"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
