name: StreamingCommunity Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install streamingcommunity-unofficialapi --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org
          pip install requests
          pip install fastapi uvicorn

      - name: Esegui server FastAPI
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 --reload &
          sleep 40  # Aumentato il tempo di attesa per essere sicuri che il server sia pronto

      - name: Verifica se il server è in esecuzione
        run: |
          curl -v http://localhost:8000

      - name: Scarica la playlist M3U8
        run: |
          curl -v -o streaming.m3u8 http://localhost:8000/playlist.m3u8

      - name: Commit e push del file M3U8 aggiornato
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add streaming.m3u8
          git commit -m "Aggiornato file M3U8 con nuovi flussi" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true