name: StreamingCommunity Scraper

on:
  workflow_dispatch:  # Permette l'esecuzione manuale
  schedule:
    - cron: '*/15 * * * *'  # Esegue ogni 15 minuti

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/Blu-Tiger/streamingcommunity-unofficialapi.git
          pip install requests

      - name: Esegui scraper StreamingCommunity
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python simudflix.py

      - name: Commit e push dei file M3U8
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add *.m3u8
          git commit -m "Aggiornati flussi M3U8" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true