name: StreamingCommunity Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install streamingcommunity-unofficialapi --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org
          pip install requests

      - name: Run SkyStreaming scraper
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python simudflix.py

      - name: Commit and push updated M3U8 file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Nascondi le modifiche non commesse (stash)
          git stash 

          # Esegui il pull prima di fare il push (con rebase per evitare conflitti)
          git pull origin main --rebase

          # Aggiungi il file M3U8 modificato
          git add streaming.m3u8
          
          # Commit delle modifiche
          git commit -m "Aggiornato file M3U8 con nuovi flussi" || echo "Nessun cambiamento da committare"

          # Push delle modifiche
          git push origin main

          # Ripristina le modifiche che erano nascoste (stash pop)
          git stash pop

        continue-on-error: true