name: Generate Streaming File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-simudflix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        # Ottieni la versione di Chrome installata
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
        echo "Chrome version: $CHROME_VERSION"

        # Recupera l'ultima versione compatibile di ChromeDriver
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        if [ -z "$CHROMEDRIVER_VERSION" ]; then
          echo "Error: Unable to retrieve ChromeDriver version for Chrome $CHROME_VERSION"
          exit 1
        fi
        echo "ChromeDriver version: $CHROMEDRIVER_VERSION"

        # Scarica e installa ChromeDriver
        wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver_linux64.zip

    - name: Run simudflix.py
      env:
        DISPLAY: :99.0  # Necessario per Selenium se non in modalità headless
      run: |
        python simudflix.py > streaming.m3u8

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add streaming.m3u8
        git commit -m "Update streaming.m3u8 file"
        git push
