name: StreamingCommunity Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # Esegui ogni 15 minuti

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudscraper beautifulsoup4

      - name: Run StreamingCommunity scraper
        run: python simudflix.py

      - name: Upload page content
        uses: actions/upload-artifact@v4
        with:
          name: page-content
          path: page_content.html
          if-no-files-found: warn

      - name: Upload iframe content
        uses: actions/upload-artifact@v4
        with:
          name: iframe-content
          path: iframe_content.html
          if-no-files-found: warn

      - name: Upload M3U8 links
        uses: actions/upload-artifact@v4
        with:
          name: m3u8-links
          path: streaming.m3u8
          if-no-files-found: warn

      - name: Commit and push updated M3U8 file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add streaming.m3u8
          git commit -m "Aggiornato file M3U8 con nuovi flussi" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true