# .github/workflows/update-m3u8.yml

name: Update streaming.m3u8

on:
  schedule:
    - cron: '0 0 * * *'  # Esegui ogni giorno a mezzanotte
  workflow_dispatch:  # Permetti l'esecuzione manuale

jobs:
  update-m3u8:
    runs-on: ubuntu-latest

    steps:
    # Checkout del repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Configura Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Installa le dipendenze
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    # Esegui lo script Python
    - name: Run script to generate streaming.m3u8
      run: |
        python it/dogior/hadEnough/streaming_community_extractor.py
      env:
        STREAMING_URL: ${{ secrets.STREAMING_URL }}  # URL del flusso

    # Commit e push del file streaming.m3u8
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add streaming.m3u8
        git commit -m "Update streaming.m3u8" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}