name: StreamingCommunity Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # Esegui ogni 15 minuti

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create build.gradle
        run: |
          cat << 'EOF' > build.gradle
          plugins {
              id 'org.jetbrains.kotlin.jvm' version '1.9.0'
              id 'application'
          }
          repositories {
              mavenCentral()
          }
          dependencies {
              implementation 'org.jsoup:jsoup:1.15.3'
              implementation 'com.squareup.okhttp3:okhttp:4.10.0'
              implementation 'org.json:json:20230227'
          }
          application {
              mainClass.set('StreamingCommunityScraperKt')
          }
          EOF

      - name: Build and run Kotlin script
        run: |
          gradle run
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2g"

      - name: Upload debug files
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: debug/*.html
          if-no-files-found: warn

      - name: Upload network requests
        uses: actions/upload-artifact@v4
        with:
          name: network-requests
          path: network_requests.log
          if-no-files-found: warn

      - name: Upload M3U8 links
        uses: actions/upload-artifact@v4
        with:
          name: m3u8-links
          path: streaming.m3u8
          if-no-files-found: warn

      - name: Commit and push updated M3U8 file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add streaming.m3u8
          git commit -m "Aggiornato file M3U8 con nuovi flussi" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true