name: Aggiorna Playlist IPTV

on:
  schedule:
    - cron: "0 */3 * * *"  # Esegui ogni 3 ore
  workflow_dispatch:  # Permette di eseguire il workflow manualmente

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 🔹 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 📦 Installa dipendenze
        run: pip install requests PyGithub

      - name: ⚡ Esegui script
        run: python script.py
        env:
          GITHUB_TOKEN: ${{ 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 }}

      - name: 📤 Commit e Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add eventi_italiani.m3u8 eventi_stranieri.m3u8
          git commit -m "Aggiornamento automatico lista IPTV"
          git push
