name: Update SkyStreaming Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:  # Aggiungi questi permessi
      contents: write  # Permette di fare push

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Importante per Git history

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraper
      run: python sky_streaming.py

    - name: Commit and Push using GitHub Script
      uses: actions/github-script@v6
      with:
      script: |
        const fs = require('fs');
        const content = fs.readFileSync('skystreaming_playlist.m3u', 'utf8');
        await github.rest.repos.createOrUpdateFileContents({
          owner: context.repo.owner,
          repo: context.repo.repo,
          path: 'skystreaming_playlist.m3u',
          message: 'Auto-update playlist',
          content: Buffer.from(content).toString('base64'),
        });
