name: Aggiorna Playlist M3U

on:
  schedule:
    - cron: '0 * * * *'  # Esegue ogni ora
  workflow_dispatch:  # Permette di avviare manualmente l'azione

jobs:
  update_playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Sostituisci con la versione di Python necessaria

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      
      - name: Run script
        run: python script.py  # Sostituisci con il nome corretto del tuo script

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add skystreaming_playlist.m3u
          git commit -m "Aggiornamento automatico della playlist M3U"
          git push
