name: Update Playlist

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permette di eseguire il workflow manualmente

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get video streams
        run: |
          # Qui dovresti eseguire il tuo script per generare la playlist M3U
          python3 update_m3u.py

      - name: Commit updated playlist
        run: |
          git add path/to/your/playlist.m3u
          git commit -m "Aggiornamento playlist"
          git push https://github-actions:${{ secrets.ACTIONS_TOKEN }}@github.com/simud/simud.git
